{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "cashdrawer-reports.fullname" . }}-pv
  labels:
    {{- include "cashdrawer-reports.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else }}
  storageClassName: manual
  {{- end }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cashdrawer-reports.fullname" . }}-pvc
  labels:
    {{- include "cashdrawer-reports.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else }}
  storageClassName: manual
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}