version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ../BullittDrawer.db:/data/BullittDrawer.db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-development-key
      - DATABASE_PATH=/data/BullittDrawer.db
      - ALLOWED_HOSTS=localhost,127.0.0.1
    command: python manage.py runserver 0.0.0.0:8000