apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashdrawer-deployment
  namespace: cashdrawer
  labels:
    app: cashdrawer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cashdrawer
  template:
    metadata:
      labels:
        app: cashdrawer
    spec:
      containers:
      - name: cashdrawer
        image: cashdrawer-reports:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cashdrawer-secret
              key: SECRET_KEY
        envFrom:
        - configMapRef:
            name: cashdrawer-config
        volumeMounts:
        - name: database-storage
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: cashdrawer-pvc